### ISSUE TITLE
80-Tooth to 20-Tooth gear connection screw: Size mismatch between sources

### ISSUE THREAD

**Issue by SobhanAbedi** [VoronDesign/Mobius-Extruder#7]
Hi. The main issue is with VoronDesing website. I think since the website is linked under VoronDesign GitHub account, it's ok to post this issue here.
The screw needed for connecting the 80-Tooth gear to 20-Tooth gear is said to be M3x6 in the BOM and Sourcing guide but in the manual and .STEP file it is M3x8. Since M3x8 doesn't have any clearance issues in the CAD, I guess they should both work fine but it would be better if the mismatch is fixed.

**Comment by telxoid** [comment]
Confirmed and pointed out by another user.  Either should work fine, but best to eliminate confusion.
